### ISSUE TITLE
Guilds without icon

### ISSUE THREAD

**Issue by julxyz** [maikdevries/Orbit#25]
Guilds without icons are displayed with a missing image. 
![image](https://user-images.githubusercontent.com/45462701/149365116-344e6b50-9294-40dc-93e9-e1218e613246.png)

**Comment by maikdevries** [comment]
This is likely due to the CDN endpoint not returning an image as there is no image to return. Instead, there's probably an endpoint that returns the 'default generated image' of the server (just two letters of the server name). Good catch!

**Comment by maikdevries** [comment]
A fix has been found where based on the presence of `guild.icon` either the icon is shown or instead a `div` with as text the first letter of each word in the server name with a maximum of 3 letters.

![image](https://user-images.githubusercontent.com/44983425/149625802-bedc5fd6-8a98-463a-b21a-b6600936e687.png)
