### ISSUE TITLE
Invite to server button isn't updated after adding bot to a guild

### ISSUE THREAD

**Issue by julxyz** [maikdevries/Orbit#26]
Steps to replicate
 - Sign in on the dashboard
 - Click invite to server on a new guild
 - Add the bot to the server
 - Go back to the dashboard
 - The dashboard will still display the "Invite to server" button

**Comment by julxyz** [comment]
Similar behavior when kicking the bot form a guild. The button should change  from "Manage server" to "Invite to server" when the bot is kicked from the guild and opening the control panel fails for the first time.

**Comment by maikdevries** [comment]
This is a side-effect of attaching the user's current guilds to the session when they log in and never refreshing them after. This is also why logging out and back in does update the dashboard. This was done to limit the number of Discord API requests which sometimes resulted in the backend being rate limited (#24).

To tackle this bug but also prevent the issue of rate limiting, the guilds should be updated each time a user loads the guild selection page. This prevents too many API requests being made but also ensures the latest information is shown at each time the user could possibly need it (there is no need to update the guilds when the user is on a guild's dashboard as they don't need other guilds other than the current one).

**Comment by maikdevries** [comment]
There are two solutions possible to fix this bug: update the `joined` property on each dashboard refresh OR do a total refresh of the list of guilds.

The second option was chosen as this also ensures that if the user joins a new guild, it will pop up on the guild selection page without having to reauthenticate. In addition, any changed guild data such as its name or icon will also be displayed properly.

However, by making this choice one has to be aware of the effect it will have on rate limiting. Refreshing the list of guilds on each page refresh is quite costly and if spammed, can run into rate limiting right away. Therefore, the additional measure was taken to have an `expires` field which defines the time the cache will expire and a complete refresh is necessary.

The current cache expiration is set to 5 seconds which prevents unnecessary rate limiting but also ensures that the most up to date information is shown up to 5 seconds old and thus will not have an effect on the user.
